version: '2'
services:
  app:
    image: "node-etherview"
    ports:
     - "127.0.0.1:3000:3000"
    volumes:
     - ./server.js:/usr/src/app/server.js
     - ./.env:/usr/src/app/.env
     - ./views:/usr/src/app/views
